# Setup
title:               AMLproject
tagline:             'A distinct core regulatory module enforces oncogene expression in KMT2A-rearranged leukemia'
description:         'A distinct core regulatory module enforces oncogene expression in KMT2A-rearranged leukemia'
url:                 https://jkobject.com
baseurl:             '/AMLproject/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeremie Kalfon
  url:               https://twitter.com/jkobject
  email:             jkobject@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
